# Generated by Django 5.1.6 on 2025-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('converted_video_file_144', models.FileField(upload_to='converted_videos_144/')),
                ('converted_video_file_380', models.FileField(upload_to='converted_videos_380/')),
                ('converted_video_file_720', models.FileField(upload_to='converted_videos_720/')),
            ],
        ),
    ]
