# Generated by Django 5.1.6 on 2025-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='converted_video_file_144',
            field=models.FileField(default=None, null=True, upload_to='converted_videos_144/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='converted_video_file_380',
            field=models.FileField(default=None, null=True, upload_to='converted_videos_380/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='converted_video_file_720',
            field=models.FileField(default=None, null=True, upload_to='converted_videos_720/'),
        ),
    ]
