# Generated by Django 5.1.6 on 2025-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videos_converted_video_file_144_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='converted_video_file_144',
            field=models.FileField(default=None, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='converted_video_file_380',
            field=models.FileField(default=None, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='converted_video_file_720',
            field=models.FileField(default=None, null=True, upload_to='videos/'),
        ),
    ]
