# Generated by Django 5.1.6 on 2025-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videos_subtitles_alter_videos_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='overview',
            field=models.TextField(default='qwqeqer'),
        ),
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.TextField(default='qwqeqer', max_length=250),
        ),
    ]
