# Generated by Django 5.1.6 on 2025-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videos_overview_videos_slug_videos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
