# Generated by Django 5.1.6 on 2025-02-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_channel_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.channel'),
            preserve_default=False,
        ),
    ]
