# Generated by Django 5.1.6 on 2025-02-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_channel_slug_videos_dislikes_videos_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
