# Generated by Django 5.1.6 on 2025-02-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_likedislike_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='video',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='videos.videos'),
        ),
    ]
