# Generated by Django 5.1.6 on 2025-02-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_likedislike_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='videos.videos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1, null=True),
        ),
    ]
