# Generated by Django 5.1.6 on 2025-02-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_alter_likedislike_video_alter_likedislike_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='views',
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videos')),
            ],
        ),
    ]
