# Generated by Django 5.1.6 on 2025-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_remove_videos_views_videoview'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
