# Generated by Django 5.1.6 on 2025-02-24 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_channel_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='overview',
            field=models.TextField(),
        ),
    ]
