# Generated by Django 5.1.6 on 2025-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_videoview_user_videoview_viewed_at_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
